config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'sessions#new'

  # these routes are for showing users a login form, logging them in, and logging them out.
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  # These routes will be for signup. The first renders a form in the browse, the second will
  # receive the form and create a user in ob
  # ur database using the data given to us by the user.
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  resources :users do
    resources :attachments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :user

  def initialize(params = {})
    @file = params.delete(:file)
    super
    if @file
      self.filename = sanitize_filename(@file.original_filename)
      self.content_type = @file.content_type
      self.data = @file.read
    end
  end

  private

  def sanitize_filename(filename)
    # Get only the filename, not the whole path (for IE)
    # Thanks to this article I just found for the tip: http://mattberther.com/2007/10/19/uploading-files-to-a-database-using-rails
    return File.basename(filename)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :attachments
  accepts_nested_attributes_for :attachments, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :authorize
  before_action :set_attachment, only: [:show, :destroy]

  def index
    @attachments = current_user.attachments
  end

  def show
    send_data(@attachment.data,
              type: @attachment.content_type,
              filename: @attachment.filename)
  end

  def new
    @attachment = current_user.attachments.build
  end

  def create
    @attachment = current_user.attachments.build(attachment_params)

    respond_to do |format|
      if @attachment.save
        flash[:notice] = "Successfully created new attachment"
        redirect_to user_attachments_path current_user.id
      else
        render :action => 'new'
      end
    end
  end

  def destroy
    @attachment.destroy
    respond_to do |format|
      format.html { redirect_to user_attachments_path current_user.id }
      format.json { head :no_content }
    end
  end

  private
  def set_attachment
    @attachment = current_user.attachments.find(params[:id])
  end

  def attachment_params
    params.require(:attachment).permit(:file)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:session][:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to user_attachments_path user.id
    else
      # If user's login doesn't work, send them back to the login form.
      flash[:error] = "Unable to login, please signup"
      redirect_to '/signup'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    @user.attachments.build
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to user_attachments_path user.id
    else
      redirect_to '/signup'
    end
  end

  def update
    user = User.find(params[:id])
    if user.attachments.create user_attachment_params
      redirect_to user_attachments_path user.id, status: 200
    else
      redirect_to user_attachments_path user.id, status: 400
    end
  end

  private
  def user_attachment_params
    params.require(:user).require(:attachment)
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attachments/_form.html.erb
<%= form_for current_user do |f| %>
  <%= f.fields_for :attachment do |ff| %>
    <div class="field">
      <%= ff.file_field :file %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attachments/index.html.erb
<h2>Listing Attachments</h2>
<table>
  <thead>
    <tr>
      <th>Filename</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @attachments.each do |attachment| %>
      <tr>
        <td><%= attachment.filename %></td>
        <td><%= button_to 'Download', user_attachment_path(current_user, attachment), method: :get %></td>
        <td><%= button_to 'Destroy', user_attachment_path(current_user, attachment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Attachment', new_user_attachment_path %>

app/views/attachments/new.html.erb
<h1>New Attachment</h1>
<%= render 'form' %>
<%= link_to 'Back', user_attachments_path(current_user.id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FileUpload</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <%= content_tag(:div, flash[:error], :class => "flash_error") if flash[:error] %>
      <%= content_tag(:div, flash[:notice], :class => "flash_notice") if flash[:notice] %>
      <%= content_tag(:div, flash[:alert], :class => "flash_alert") if flash[:alert] %>
      <div class="header">
        <% if current_user %>
          Signed in as <%= current_user.name %> | <%= link_to "Logout", '/logout' %>
        <% else %>
          <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<div class="signup">
  <div class="form">
    <h1>Sign up</h1>
    <%= form_for(@user) do |f| %>
      <%= f.text_field :name, :placeholder => "Name" %>
      <%= f.email_field :email, :placeholder => "Email" %>
      <%= f.password_field :password, :placeholder => "Password" %>
      <%= f.submit "Create an account", class: "btn-submit" %>
    <% end %>
  </div>
</div>